dataset_path: lmms-lab/MMMU
task: "mmmu_val"
test_split: validation
output_type: generate_until
doc_to_visual: !function utils.mmmu_doc_to_visual
doc_to_text: !function utils.mmmu_doc_to_text
doc_to_target: "answer"
# The return value of process_results will be used by metrics
process_results: !function utils.mmmu_process_results
generation_kwargs:
  max_new_tokens: 2048

metric_list:
  - metric: mmmu_acc
    aggregation: !function utils.mmmu_aggregate_results
    higher_is_better: true

lmms_eval_specific_kwargs:
  default:
    prompt_type: "format"
    multiple_choice_prompt: "Write your final answer directly in the format 'Answer: X' where X is the option's letter from the given choices. If the answer is not in the choices, please give the closest option."
    open_ended_prompt: "Write your final answer directly in the format 'Answer: X' where X is a single word or phrase that answers the question."
include: _default_template_yaml